name: Deploy to SiteGround

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        env:
          REACT_APP_BE_ENDPOINT: ${{ secrets.REACT_APP_BE_ENDPOINT }}
        run: npm run build

      - name: Set up SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SG_SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.SG_PORT }} ${{ secrets.SG_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy via SSH using Rsync
        run: |
          rsync -avz --progress --exclude=".htaccess" -e "ssh -p ${{ secrets.SG_PORT }}" ./build/ ${{ secrets.SG_USER }}@${{ secrets.SG_HOST }}:www/shop.lakeshorelabradoodles.com/public_html/
